### PR TITLE
feat: allow validating multiple definitions at once in the cli

### LINKED ISSUE #137: Support validating multiple files at once
**Is your feature request related to a problem? Please describe.**
This is somewhat of a bug and somewhat of a feature request - at present, `asl-validator` needs to be invoked once per file to be checked and doesn't support checking multiple files simultaneously, such as:

```sh
asl-validator --json-path statemachine/*.asl.json
asl-validator --json-path statemachine/foo.asl.json statemachine/bar.asl.json ...
```

The bug aspect of this is that when invoked with multiple filenames the validator will only check the first one specified and silently ignore the rest. In the example above, if `foo.asl.json` is valid but `bar.asl.json` isn't, then a success message will be printed as only the first file gets checked.

Having the ability to check multiple files at once makes processing faster as only one instance of the validator is needed to test any number of files; this becomes increasingly more of an issue with more state machine definitions. From a user's perspective, it simplifies use of the tool by allowing globbing, as above, where multiple ASLs can to be checked without needing to name files individually and re-run the validator separately for each. Adding multiple file support would also make this tool compatible with https://pre-commit.com/, for use as a pre-commit Git hook.

**Describe the solution you'd like**
Support for multiple files to be validated in one run, such that the command examples given above are possible.

In addition, console output doesn't currently indicate which ASL definition file has succeeded or failed, so that would need to be added for clarity, such as:

```sh
✓ State machine definition is valid (statemachine/foo.asl.json)
✕ State machine definition is invalid (statemachine/bar.asl.json):
 MISSING_TRANSITION_TARGET: State Process Data is not reachable
MISSING_TRANSITION_TARGET: Missing 'StartAt'|'Next'|'Default' target: Process Data
``` 

**Describe alternatives you've considered**
I'm currently wrapping `asl-validator` in shell loops and Makefiles so as invoking it one at a time for each file, echoing out the filename being checked so I know which fails and when, and taking care not to call the app with multiple paths to avoid the bug.

**Additional context**

### PR DESCRIPTION
**Pull request by ChristopheBougere**
Fixes #137 and #136

@davidjb this PR make it possible to validate multiple definitions at once and now support yaml. Would you mind having a look and let me know if it fixes your issues?

You can give it a try by checking out this branch, running `npm install` and running with `npx ts-node`

For instance:

```bash
npx ts-node ./bin/asl-validator.ts --json-path src/__tests__/definitions/valid-cfn-definition-substitutions.json --json-path src/__tests__/definitions/valid-catch-failure.json --yaml-definition "{}"
```

Which validates 2 json paths and 1 yaml definition, should output:

```
✓ State machine definition "src/__tests__/definitions/valid-cfn-definition-substitutions.json" is valid
✓ State machine definition "src/__tests__/definitions/valid-catch-failure.json" is valid
✕ State machine definition "YAML definition #1" is invalid:
 SCHEMA_VALIDATION_FAILED:  is invalid. must have required property 'StartAt'
```

### CODE REVIEW

**Comment by jftuga** [comment]
Just confirming this also fixes some issues I was having with multiple files.  I can now add `asl-validator` to my pipeline!

Thank you!

**Comment by davidjb** [comment]
@ChristopheBougere Thanks a lot for implementing this. Unfortunately needing to re-specify the type of the input/file between each filename means that globbing isn't feasible, e.g. 

```sh
asl-validator --yaml-path statemachine/*.asl.yml
```

which gets expanded out to passing file names as later arguments:

```sh
asl-validator --yaml-path statemachine/one.asl.yml statemachine/two.asl.yml statemachine/three.asl.yml ...
```

This sort of varargs pattern is how both the shell globbing and pre-commit hooks framework works.
 
In other words, a user can check multiple files but still needs to explicitly name each file and its respective type one after the other as the path arguments differ. On this, needing to specify the type of the input (e.g. `--yaml-path`, `--json-path`) means it isn't feasible to generically call the validator, such as:

```sh
asl-validator --path *
asl-validator --path statemachine/*
asl-validator --path statemachine/*.{yaml,yml,json}
```

because you need to tell the validator the type ahead of time. This is less of an issue as you could invoke the validator once for JSON and once for YAML if a variable number of paths were able to be supported.

**Comment by jftuga** [comment]
@davidjb I agree with your suggestion.  Here is a work around in bash:

    ASL=$(ls *yml | awk '{a = a "--yaml-path="$1" "} END {print "asl-validator "a}')
    ${ASL}

**Comment by ChristopheBougere** [comment]
Thanks for the feedback @davidjb 
Does @jftuga work around solves your issue?

**Comment by davidjb** [comment]
@ChristopheBougere No, not really - I appreciate the workaround but wouldn't say it solves the issue. A workaround like that isn't easily typed and would need a conditional to handle JSON/YAML differently given the requirement to tell the linter the type via an argument. All that could perhaps be aliased in your shell, but then a call to the validator depends on a subshell, piping and an awk program - and becomes brittle if/when `asl-validator` changes.

Typically, linters will default to taking a list of files/directories to lint as varargs (e.g. JavaScript's [eslint](https://eslint.org/docs/latest/use/command-line-interface#run-the-cli) or Python's [Black](https://github.com/psf/black#usage))and processes the files and/or directories' contents recursively, with the linter figuring out the specifics internally.

**Pull request merged**
